# Configuration for materials property prediction framework
experiment_name: "materials_prediction_v1"
mlflow_uri: "mlruns"
target_property: "formation_energy"

# Models to train
models_to_train:
  - cgcnn
  - deep_gatgnn
  - soap
  - sm
  - gatgnn
  - gcn
  - megnet
  - mpnn
  - schnet
  - super_cgcnn
  - super_megnet
  - super_mpnn
  - super_schnet
  - quantum_gan

# Base model parameters
model_params:
  base:
    node_features: 32
    edge_features: 16
    hidden_dim: 64
    output_dim: 1
    dropout_rate: 0.1
  
  # Model-specific parameters
  quantum_gan:
    num_qubits: 5
    layer_style: "Controlled-Dual"
    num_conv_layers: 3
    num_measurements: 500
    shots_per_measurement: 20
    backend: "qasm_simulator"
  
  soap:
    soap_dim: 1000
    num_layers: 3
  
  sm:
    sm_dim: 500
    num_layers: 3
  
  schnet:
    num_filters: 64
    num_interactions: 3
    cutoff: 8.0

  megnet:
    global_features: 108
    num_blocks: 3

# Training parameters
training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  gradient_clip_norm: 1.0

  compile_params:
    optimizer:
      class_name: "Adam"
      config:
        learning_rate: 0.001
    loss: "MeanSquaredError"
    metrics: 
      - "MeanAbsoluteError"
      - "RootMeanSquaredError"

  early_stopping:
    monitor: "val_loss"
    patience: 10
    restore_best_weights: true

  reduce_lr:
    monitor: "val_loss"
    factor: 0.5
    patience: 5
    min_lr: 0.00001

# Evaluation parameters
evaluation:
  mc_samples: 10  # For uncertainty estimation
  metrics:
    - "mae"
    - "rmse"
    - "r2"
